# Generated by Django 5.0 on 2023-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('movie_name', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='pics')),
                ('poster', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('screen', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
